//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Hengam.Reports.ReportDataSets {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsEmployeeInformation")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsEmployeeInformation : global::System.Data.DataSet {
        
        private viwRptEmployeeInformationDataTable tableviwRptEmployeeInformation;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public dsEmployeeInformation() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected dsEmployeeInformation(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["viwRptEmployeeInformation"] != null)) {
                    base.Tables.Add(new viwRptEmployeeInformationDataTable(ds.Tables["viwRptEmployeeInformation"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public viwRptEmployeeInformationDataTable viwRptEmployeeInformation {
            get {
                return this.tableviwRptEmployeeInformation;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsEmployeeInformation cln = ((dsEmployeeInformation)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["viwRptEmployeeInformation"] != null)) {
                    base.Tables.Add(new viwRptEmployeeInformationDataTable(ds.Tables["viwRptEmployeeInformation"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableviwRptEmployeeInformation = ((viwRptEmployeeInformationDataTable)(base.Tables["viwRptEmployeeInformation"]));
            if ((initTable == true)) {
                if ((this.tableviwRptEmployeeInformation != null)) {
                    this.tableviwRptEmployeeInformation.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsEmployeeInformation";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsEmployeeInformation.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableviwRptEmployeeInformation = new viwRptEmployeeInformationDataTable();
            base.Tables.Add(this.tableviwRptEmployeeInformation);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeviwRptEmployeeInformation() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsEmployeeInformation ds = new dsEmployeeInformation();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void viwRptEmployeeInformationRowChangeEventHandler(object sender, viwRptEmployeeInformationRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class viwRptEmployeeInformationDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnemployeeID;
            
            private global::System.Data.DataColumn columnfirstName;
            
            private global::System.Data.DataColumn columnlastName;
            
            private global::System.Data.DataColumn columnfatherName;
            
            private global::System.Data.DataColumn columngender;
            
            private global::System.Data.DataColumn columncertificationNumber;
            
            private global::System.Data.DataColumn columnnationalNumber;
            
            private global::System.Data.DataColumn columnbirthDate;
            
            private global::System.Data.DataColumn columnbornPlace;
            
            private global::System.Data.DataColumn columnbornProvince;
            
            private global::System.Data.DataColumn columnbornCountry;
            
            private global::System.Data.DataColumn columnissuePlace;
            
            private global::System.Data.DataColumn columnmartialStatus;
            
            private global::System.Data.DataColumn columnhomeAddress;
            
            private global::System.Data.DataColumn columnhomeTell;
            
            private global::System.Data.DataColumn columncellPhone;
            
            private global::System.Data.DataColumn columndegreeTypeID;
            
            private global::System.Data.DataColumn columndegreeLevelID;
            
            private global::System.Data.DataColumn columnstudyMajor;
            
            private global::System.Data.DataColumn columnstudyStatus;
            
            private global::System.Data.DataColumn columnjob;
            
            private global::System.Data.DataColumn columnhowtoFindID;
            
            private global::System.Data.DataColumn columnschool;
            
            private global::System.Data.DataColumn columnactivityStatus;
            
            private global::System.Data.DataColumn columnguarantorID;
            
            private global::System.Data.DataColumn columnimage;
            
            private global::System.Data.DataColumn columnguarantorName;
            
            private global::System.Data.DataColumn columndegreeLevelName;
            
            private global::System.Data.DataColumn columndegreeTypeName;
            
            private global::System.Data.DataColumn columnhowtoFindName;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public viwRptEmployeeInformationDataTable() {
                this.TableName = "viwRptEmployeeInformation";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal viwRptEmployeeInformationDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected viwRptEmployeeInformationDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn employeeIDColumn {
                get {
                    return this.columnemployeeID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn firstNameColumn {
                get {
                    return this.columnfirstName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn lastNameColumn {
                get {
                    return this.columnlastName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fatherNameColumn {
                get {
                    return this.columnfatherName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn genderColumn {
                get {
                    return this.columngender;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn certificationNumberColumn {
                get {
                    return this.columncertificationNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn nationalNumberColumn {
                get {
                    return this.columnnationalNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn birthDateColumn {
                get {
                    return this.columnbirthDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn bornPlaceColumn {
                get {
                    return this.columnbornPlace;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn bornProvinceColumn {
                get {
                    return this.columnbornProvince;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn bornCountryColumn {
                get {
                    return this.columnbornCountry;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn issuePlaceColumn {
                get {
                    return this.columnissuePlace;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn martialStatusColumn {
                get {
                    return this.columnmartialStatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn homeAddressColumn {
                get {
                    return this.columnhomeAddress;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn homeTellColumn {
                get {
                    return this.columnhomeTell;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn cellPhoneColumn {
                get {
                    return this.columncellPhone;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn degreeTypeIDColumn {
                get {
                    return this.columndegreeTypeID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn degreeLevelIDColumn {
                get {
                    return this.columndegreeLevelID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn studyMajorColumn {
                get {
                    return this.columnstudyMajor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn studyStatusColumn {
                get {
                    return this.columnstudyStatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn jobColumn {
                get {
                    return this.columnjob;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn howtoFindIDColumn {
                get {
                    return this.columnhowtoFindID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn schoolColumn {
                get {
                    return this.columnschool;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn activityStatusColumn {
                get {
                    return this.columnactivityStatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn guarantorIDColumn {
                get {
                    return this.columnguarantorID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn imageColumn {
                get {
                    return this.columnimage;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn guarantorNameColumn {
                get {
                    return this.columnguarantorName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn degreeLevelNameColumn {
                get {
                    return this.columndegreeLevelName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn degreeTypeNameColumn {
                get {
                    return this.columndegreeTypeName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn howtoFindNameColumn {
                get {
                    return this.columnhowtoFindName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public viwRptEmployeeInformationRow this[int index] {
                get {
                    return ((viwRptEmployeeInformationRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event viwRptEmployeeInformationRowChangeEventHandler viwRptEmployeeInformationRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event viwRptEmployeeInformationRowChangeEventHandler viwRptEmployeeInformationRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event viwRptEmployeeInformationRowChangeEventHandler viwRptEmployeeInformationRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event viwRptEmployeeInformationRowChangeEventHandler viwRptEmployeeInformationRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddviwRptEmployeeInformationRow(viwRptEmployeeInformationRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public viwRptEmployeeInformationRow AddviwRptEmployeeInformationRow(
                        string employeeID, 
                        string firstName, 
                        string lastName, 
                        string fatherName, 
                        bool gender, 
                        string certificationNumber, 
                        string nationalNumber, 
                        string birthDate, 
                        string bornPlace, 
                        string bornProvince, 
                        string bornCountry, 
                        string issuePlace, 
                        bool martialStatus, 
                        string homeAddress, 
                        string homeTell, 
                        string cellPhone, 
                        int degreeTypeID, 
                        int degreeLevelID, 
                        string studyMajor, 
                        bool studyStatus, 
                        string job, 
                        int howtoFindID, 
                        string school, 
                        bool activityStatus, 
                        string guarantorID, 
                        byte[] image, 
                        string guarantorName, 
                        string degreeLevelName, 
                        string degreeTypeName, 
                        string howtoFindName) {
                viwRptEmployeeInformationRow rowviwRptEmployeeInformationRow = ((viwRptEmployeeInformationRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        employeeID,
                        firstName,
                        lastName,
                        fatherName,
                        gender,
                        certificationNumber,
                        nationalNumber,
                        birthDate,
                        bornPlace,
                        bornProvince,
                        bornCountry,
                        issuePlace,
                        martialStatus,
                        homeAddress,
                        homeTell,
                        cellPhone,
                        degreeTypeID,
                        degreeLevelID,
                        studyMajor,
                        studyStatus,
                        job,
                        howtoFindID,
                        school,
                        activityStatus,
                        guarantorID,
                        image,
                        guarantorName,
                        degreeLevelName,
                        degreeTypeName,
                        howtoFindName};
                rowviwRptEmployeeInformationRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowviwRptEmployeeInformationRow);
                return rowviwRptEmployeeInformationRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public viwRptEmployeeInformationRow FindByemployeeID(string employeeID) {
                return ((viwRptEmployeeInformationRow)(this.Rows.Find(new object[] {
                            employeeID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                viwRptEmployeeInformationDataTable cln = ((viwRptEmployeeInformationDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new viwRptEmployeeInformationDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnemployeeID = base.Columns["employeeID"];
                this.columnfirstName = base.Columns["firstName"];
                this.columnlastName = base.Columns["lastName"];
                this.columnfatherName = base.Columns["fatherName"];
                this.columngender = base.Columns["gender"];
                this.columncertificationNumber = base.Columns["certificationNumber"];
                this.columnnationalNumber = base.Columns["nationalNumber"];
                this.columnbirthDate = base.Columns["birthDate"];
                this.columnbornPlace = base.Columns["bornPlace"];
                this.columnbornProvince = base.Columns["bornProvince"];
                this.columnbornCountry = base.Columns["bornCountry"];
                this.columnissuePlace = base.Columns["issuePlace"];
                this.columnmartialStatus = base.Columns["martialStatus"];
                this.columnhomeAddress = base.Columns["homeAddress"];
                this.columnhomeTell = base.Columns["homeTell"];
                this.columncellPhone = base.Columns["cellPhone"];
                this.columndegreeTypeID = base.Columns["degreeTypeID"];
                this.columndegreeLevelID = base.Columns["degreeLevelID"];
                this.columnstudyMajor = base.Columns["studyMajor"];
                this.columnstudyStatus = base.Columns["studyStatus"];
                this.columnjob = base.Columns["job"];
                this.columnhowtoFindID = base.Columns["howtoFindID"];
                this.columnschool = base.Columns["school"];
                this.columnactivityStatus = base.Columns["activityStatus"];
                this.columnguarantorID = base.Columns["guarantorID"];
                this.columnimage = base.Columns["image"];
                this.columnguarantorName = base.Columns["guarantorName"];
                this.columndegreeLevelName = base.Columns["degreeLevelName"];
                this.columndegreeTypeName = base.Columns["degreeTypeName"];
                this.columnhowtoFindName = base.Columns["howtoFindName"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnemployeeID = new global::System.Data.DataColumn("employeeID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnemployeeID);
                this.columnfirstName = new global::System.Data.DataColumn("firstName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfirstName);
                this.columnlastName = new global::System.Data.DataColumn("lastName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlastName);
                this.columnfatherName = new global::System.Data.DataColumn("fatherName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfatherName);
                this.columngender = new global::System.Data.DataColumn("gender", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columngender);
                this.columncertificationNumber = new global::System.Data.DataColumn("certificationNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncertificationNumber);
                this.columnnationalNumber = new global::System.Data.DataColumn("nationalNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnationalNumber);
                this.columnbirthDate = new global::System.Data.DataColumn("birthDate", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbirthDate);
                this.columnbornPlace = new global::System.Data.DataColumn("bornPlace", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbornPlace);
                this.columnbornProvince = new global::System.Data.DataColumn("bornProvince", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbornProvince);
                this.columnbornCountry = new global::System.Data.DataColumn("bornCountry", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbornCountry);
                this.columnissuePlace = new global::System.Data.DataColumn("issuePlace", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnissuePlace);
                this.columnmartialStatus = new global::System.Data.DataColumn("martialStatus", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmartialStatus);
                this.columnhomeAddress = new global::System.Data.DataColumn("homeAddress", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhomeAddress);
                this.columnhomeTell = new global::System.Data.DataColumn("homeTell", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhomeTell);
                this.columncellPhone = new global::System.Data.DataColumn("cellPhone", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncellPhone);
                this.columndegreeTypeID = new global::System.Data.DataColumn("degreeTypeID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndegreeTypeID);
                this.columndegreeLevelID = new global::System.Data.DataColumn("degreeLevelID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndegreeLevelID);
                this.columnstudyMajor = new global::System.Data.DataColumn("studyMajor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstudyMajor);
                this.columnstudyStatus = new global::System.Data.DataColumn("studyStatus", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstudyStatus);
                this.columnjob = new global::System.Data.DataColumn("job", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnjob);
                this.columnhowtoFindID = new global::System.Data.DataColumn("howtoFindID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhowtoFindID);
                this.columnschool = new global::System.Data.DataColumn("school", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnschool);
                this.columnactivityStatus = new global::System.Data.DataColumn("activityStatus", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnactivityStatus);
                this.columnguarantorID = new global::System.Data.DataColumn("guarantorID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnguarantorID);
                this.columnimage = new global::System.Data.DataColumn("image", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnimage);
                this.columnguarantorName = new global::System.Data.DataColumn("guarantorName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnguarantorName);
                this.columndegreeLevelName = new global::System.Data.DataColumn("degreeLevelName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndegreeLevelName);
                this.columndegreeTypeName = new global::System.Data.DataColumn("degreeTypeName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndegreeTypeName);
                this.columnhowtoFindName = new global::System.Data.DataColumn("howtoFindName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhowtoFindName);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnemployeeID}, true));
                this.columnemployeeID.AllowDBNull = false;
                this.columnemployeeID.Unique = true;
                this.columnemployeeID.MaxLength = 10;
                this.columnfirstName.AllowDBNull = false;
                this.columnfirstName.MaxLength = 50;
                this.columnlastName.MaxLength = 50;
                this.columnfatherName.MaxLength = 50;
                this.columngender.AllowDBNull = false;
                this.columncertificationNumber.MaxLength = 20;
                this.columnnationalNumber.MaxLength = 10;
                this.columnbirthDate.MaxLength = 10;
                this.columnbornPlace.MaxLength = 50;
                this.columnbornProvince.MaxLength = 50;
                this.columnbornCountry.MaxLength = 50;
                this.columnissuePlace.MaxLength = 50;
                this.columnmartialStatus.AllowDBNull = false;
                this.columnhomeAddress.MaxLength = 200;
                this.columnhomeTell.MaxLength = 20;
                this.columncellPhone.MaxLength = 20;
                this.columnstudyMajor.MaxLength = 100;
                this.columnstudyStatus.AllowDBNull = false;
                this.columnjob.MaxLength = 100;
                this.columnschool.MaxLength = 100;
                this.columnactivityStatus.AllowDBNull = false;
                this.columnguarantorID.MaxLength = 10;
                this.columnguarantorName.ReadOnly = true;
                this.columnguarantorName.MaxLength = 101;
                this.columndegreeLevelName.AllowDBNull = false;
                this.columndegreeLevelName.MaxLength = 100;
                this.columndegreeTypeName.MaxLength = 100;
                this.columnhowtoFindName.MaxLength = 200;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public viwRptEmployeeInformationRow NewviwRptEmployeeInformationRow() {
                return ((viwRptEmployeeInformationRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new viwRptEmployeeInformationRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(viwRptEmployeeInformationRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.viwRptEmployeeInformationRowChanged != null)) {
                    this.viwRptEmployeeInformationRowChanged(this, new viwRptEmployeeInformationRowChangeEvent(((viwRptEmployeeInformationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.viwRptEmployeeInformationRowChanging != null)) {
                    this.viwRptEmployeeInformationRowChanging(this, new viwRptEmployeeInformationRowChangeEvent(((viwRptEmployeeInformationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.viwRptEmployeeInformationRowDeleted != null)) {
                    this.viwRptEmployeeInformationRowDeleted(this, new viwRptEmployeeInformationRowChangeEvent(((viwRptEmployeeInformationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.viwRptEmployeeInformationRowDeleting != null)) {
                    this.viwRptEmployeeInformationRowDeleting(this, new viwRptEmployeeInformationRowChangeEvent(((viwRptEmployeeInformationRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveviwRptEmployeeInformationRow(viwRptEmployeeInformationRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsEmployeeInformation ds = new dsEmployeeInformation();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "viwRptEmployeeInformationDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class viwRptEmployeeInformationRow : global::System.Data.DataRow {
            
            private viwRptEmployeeInformationDataTable tableviwRptEmployeeInformation;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal viwRptEmployeeInformationRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableviwRptEmployeeInformation = ((viwRptEmployeeInformationDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string employeeID {
                get {
                    return ((string)(this[this.tableviwRptEmployeeInformation.employeeIDColumn]));
                }
                set {
                    this[this.tableviwRptEmployeeInformation.employeeIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string firstName {
                get {
                    return ((string)(this[this.tableviwRptEmployeeInformation.firstNameColumn]));
                }
                set {
                    this[this.tableviwRptEmployeeInformation.firstNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string lastName {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.lastNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'lastName\' in table \'viwRptEmployeeInformation\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.lastNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fatherName {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.fatherNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fatherName\' in table \'viwRptEmployeeInformation\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.fatherNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool gender {
                get {
                    return ((bool)(this[this.tableviwRptEmployeeInformation.genderColumn]));
                }
                set {
                    this[this.tableviwRptEmployeeInformation.genderColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string certificationNumber {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.certificationNumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'certificationNumber\' in table \'viwRptEmployeeInformation\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.certificationNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string nationalNumber {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.nationalNumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nationalNumber\' in table \'viwRptEmployeeInformation\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.nationalNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string birthDate {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.birthDateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'birthDate\' in table \'viwRptEmployeeInformation\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.birthDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string bornPlace {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.bornPlaceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bornPlace\' in table \'viwRptEmployeeInformation\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.bornPlaceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string bornProvince {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.bornProvinceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bornProvince\' in table \'viwRptEmployeeInformation\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.bornProvinceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string bornCountry {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.bornCountryColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bornCountry\' in table \'viwRptEmployeeInformation\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.bornCountryColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string issuePlace {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.issuePlaceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'issuePlace\' in table \'viwRptEmployeeInformation\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.issuePlaceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool martialStatus {
                get {
                    return ((bool)(this[this.tableviwRptEmployeeInformation.martialStatusColumn]));
                }
                set {
                    this[this.tableviwRptEmployeeInformation.martialStatusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string homeAddress {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.homeAddressColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'homeAddress\' in table \'viwRptEmployeeInformation\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.homeAddressColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string homeTell {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.homeTellColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'homeTell\' in table \'viwRptEmployeeInformation\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.homeTellColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string cellPhone {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.cellPhoneColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'cellPhone\' in table \'viwRptEmployeeInformation\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.cellPhoneColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int degreeTypeID {
                get {
                    try {
                        return ((int)(this[this.tableviwRptEmployeeInformation.degreeTypeIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'degreeTypeID\' in table \'viwRptEmployeeInformation\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.degreeTypeIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int degreeLevelID {
                get {
                    try {
                        return ((int)(this[this.tableviwRptEmployeeInformation.degreeLevelIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'degreeLevelID\' in table \'viwRptEmployeeInformation\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.degreeLevelIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string studyMajor {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.studyMajorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'studyMajor\' in table \'viwRptEmployeeInformation\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.studyMajorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool studyStatus {
                get {
                    return ((bool)(this[this.tableviwRptEmployeeInformation.studyStatusColumn]));
                }
                set {
                    this[this.tableviwRptEmployeeInformation.studyStatusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string job {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.jobColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'job\' in table \'viwRptEmployeeInformation\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.jobColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int howtoFindID {
                get {
                    try {
                        return ((int)(this[this.tableviwRptEmployeeInformation.howtoFindIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'howtoFindID\' in table \'viwRptEmployeeInformation\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.howtoFindIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string school {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.schoolColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'school\' in table \'viwRptEmployeeInformation\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.schoolColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool activityStatus {
                get {
                    return ((bool)(this[this.tableviwRptEmployeeInformation.activityStatusColumn]));
                }
                set {
                    this[this.tableviwRptEmployeeInformation.activityStatusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string guarantorID {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.guarantorIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'guarantorID\' in table \'viwRptEmployeeInformation\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.guarantorIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte[] image {
                get {
                    try {
                        return ((byte[])(this[this.tableviwRptEmployeeInformation.imageColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'image\' in table \'viwRptEmployeeInformation\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.imageColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string guarantorName {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.guarantorNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'guarantorName\' in table \'viwRptEmployeeInformation\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.guarantorNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string degreeLevelName {
                get {
                    return ((string)(this[this.tableviwRptEmployeeInformation.degreeLevelNameColumn]));
                }
                set {
                    this[this.tableviwRptEmployeeInformation.degreeLevelNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string degreeTypeName {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.degreeTypeNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'degreeTypeName\' in table \'viwRptEmployeeInformation\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.degreeTypeNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string howtoFindName {
                get {
                    try {
                        return ((string)(this[this.tableviwRptEmployeeInformation.howtoFindNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'howtoFindName\' in table \'viwRptEmployeeInformation\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableviwRptEmployeeInformation.howtoFindNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IslastNameNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.lastNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetlastNameNull() {
                this[this.tableviwRptEmployeeInformation.lastNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsfatherNameNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.fatherNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetfatherNameNull() {
                this[this.tableviwRptEmployeeInformation.fatherNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IscertificationNumberNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.certificationNumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetcertificationNumberNull() {
                this[this.tableviwRptEmployeeInformation.certificationNumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsnationalNumberNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.nationalNumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetnationalNumberNull() {
                this[this.tableviwRptEmployeeInformation.nationalNumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsbirthDateNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.birthDateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetbirthDateNull() {
                this[this.tableviwRptEmployeeInformation.birthDateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsbornPlaceNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.bornPlaceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetbornPlaceNull() {
                this[this.tableviwRptEmployeeInformation.bornPlaceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsbornProvinceNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.bornProvinceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetbornProvinceNull() {
                this[this.tableviwRptEmployeeInformation.bornProvinceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsbornCountryNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.bornCountryColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetbornCountryNull() {
                this[this.tableviwRptEmployeeInformation.bornCountryColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsissuePlaceNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.issuePlaceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetissuePlaceNull() {
                this[this.tableviwRptEmployeeInformation.issuePlaceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IshomeAddressNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.homeAddressColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SethomeAddressNull() {
                this[this.tableviwRptEmployeeInformation.homeAddressColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IshomeTellNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.homeTellColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SethomeTellNull() {
                this[this.tableviwRptEmployeeInformation.homeTellColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IscellPhoneNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.cellPhoneColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetcellPhoneNull() {
                this[this.tableviwRptEmployeeInformation.cellPhoneColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsdegreeTypeIDNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.degreeTypeIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetdegreeTypeIDNull() {
                this[this.tableviwRptEmployeeInformation.degreeTypeIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsdegreeLevelIDNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.degreeLevelIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetdegreeLevelIDNull() {
                this[this.tableviwRptEmployeeInformation.degreeLevelIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsstudyMajorNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.studyMajorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetstudyMajorNull() {
                this[this.tableviwRptEmployeeInformation.studyMajorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsjobNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.jobColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetjobNull() {
                this[this.tableviwRptEmployeeInformation.jobColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IshowtoFindIDNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.howtoFindIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SethowtoFindIDNull() {
                this[this.tableviwRptEmployeeInformation.howtoFindIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsschoolNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.schoolColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetschoolNull() {
                this[this.tableviwRptEmployeeInformation.schoolColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsguarantorIDNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.guarantorIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetguarantorIDNull() {
                this[this.tableviwRptEmployeeInformation.guarantorIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsimageNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.imageColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetimageNull() {
                this[this.tableviwRptEmployeeInformation.imageColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsguarantorNameNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.guarantorNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetguarantorNameNull() {
                this[this.tableviwRptEmployeeInformation.guarantorNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsdegreeTypeNameNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.degreeTypeNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetdegreeTypeNameNull() {
                this[this.tableviwRptEmployeeInformation.degreeTypeNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IshowtoFindNameNull() {
                return this.IsNull(this.tableviwRptEmployeeInformation.howtoFindNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SethowtoFindNameNull() {
                this[this.tableviwRptEmployeeInformation.howtoFindNameColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class viwRptEmployeeInformationRowChangeEvent : global::System.EventArgs {
            
            private viwRptEmployeeInformationRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public viwRptEmployeeInformationRowChangeEvent(viwRptEmployeeInformationRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public viwRptEmployeeInformationRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591